
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  username: postgres
  password: Legit-gcp-db
  database: development
  host: 127.0.0.1
  port: 5400